routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');
Route::post('reset', 'Api\PasswordResetController@reset')->name('reset.password.api');
Auth::routes(['verify' => true]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth' => 'dashboard']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/subscriber', 'SubscribeController@index')->name('subscribe.index');
    Route::get('/subscriber/show/{pointer}', 'SubscribeController@show')->name('subscribe.show');

    Route::get('/member', 'MemberController@index')->name('member.index');
    Route::get('/member/show/{pointer}', 'MemberController@show')->name('member.show');

    Route::get('/contributor', 'DonationController@index')->name('contributor.index');
    Route::get('/contributor/show/{pointer}', 'DonationController@show')->name('contributor.show');

    Route::resource('event', 'EventController');

    Route::resource('book', 'BookController');

    Route::resource('ads', 'AdsController');

    Route::resource('categories', 'CategoriesController');
    Route::get('/googlecloud', 'CategoriesController@googlecloud')->name('categories.googlecloud');
    Route::post('/googlecloud', 'CategoriesController@googlecloudUpload')->name('categories.googlecloudUpload');
    Route::get('/googlecloud/op', 'CategoriesController@googlecloudOpen')->name('categories.googlecloudOpen');

});

resources/views/partials/_footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2020 <div class="bullet"></div> Develope By <a href="http://mygoodnews.id/">MyGoodnews</a>
    </div>
    <div class="footer-right">
        1.1.0
    </div>
</footer>

resources/views/partials/_head.blade.php
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Dashboard &mdash; BEC</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ asset('modules/bootstrap-daterangepicker/daterangepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('modules/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('modules/selectric/public/selectric.css') }}">
    <link rel="stylesheet" href="{{ asset('modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/components.css') }}">

    @yield('extra_styles')
</head>

resources/views/partials/_navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">
{{--        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>--}}
{{--            <div class="dropdown-menu dropdown-list dropdown-menu-right">--}}
{{--                <div class="dropdown-header">Notifications--}}
{{--                    <div class="float-right">--}}
{{--                        <a href="#">Mark All As Read</a>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="dropdown-list-content dropdown-list-icons">--}}
{{--                    <a href="#" class="dropdown-item dropdown-item-unread">--}}
{{--                        <div class="dropdown-item-icon bg-primary text-white">--}}
{{--                            <i class="fas fa-code"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            Template update is available now!--}}
{{--                            <div class="time text-primary">2 Min Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-info text-white">--}}
{{--                            <i class="far fa-user"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            <b>You</b> and <b>Dedik Sugiharto</b> are now friends--}}
{{--                            <div class="time">10 Hours Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-success text-white">--}}
{{--                            <i class="fas fa-check"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>--}}
{{--                            <div class="time">12 Hours Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-danger text-white">--}}
{{--                            <i class="fas fa-exclamation-triangle"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            Low disk space. Let's clean it!--}}
{{--                            <div class="time">17 Hours Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-info text-white">--}}
{{--                            <i class="fas fa-bell"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            Welcome to Stisla template!--}}
{{--                            <div class="time">Yesterday</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--                <div class="dropdown-footer text-center">--}}
{{--                    <a href="#">View All <i class="fas fa-chevron-right"></i></a>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </li>--}}
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }} </div></a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/partials/_script.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="{{ asset('js/stisla.js') }}"></script>

<script src="{{ asset('modules/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ asset('modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('modules/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}"></script>
<script src="{{ asset('modules/summernote/dist/summernote-bs4.js') }}"></script>
{{-- <script src="{{ asset('modules/selectric/public/jquery.selectric.min.js') }}"></script> --}}
<script src="{{ asset('modules/jquery_upload_preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script src="{{ asset('modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>

<!-- Template JS File -->
<script src="{{ asset('js/scripts.js') }}"></script>
<script src="{{ asset('js/custom.js') }}"></script>

<!-- Page Specific JS File -->
<script src="{{ asset('js/page/index.js') }}"></script>
<script src="{{ asset('js/page/modules-datatables.js') }}"></script>
<script src="{{ asset('js/page/features-post-create.js') }}"></script>
<script src="{{ asset('js/page/bootstrap-modal.js') }}"></script>
{{-- <script type="text/javascript"> 

        $('#img').attr('draggable', false); 
</script>  --}}
@yield('extra_scripts')

resources/views/partials/_sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ route('home') }}">Buddhist Education Centre</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('home') }}">LBEC</a>
        </div>
        <ul class="sidebar-menu">
            <li><a class="nav-link" href="{{ route('home') }}"><i class="fas fa-fire"></i><span>Dashboard</span></a></li>
            <li><a class="nav-link" href="{{ route('subscribe.index') }}"><i class="fas fa-ellipsis-h"></i><span>Subscriber</span></a></li>
            <li><a class="nav-link" href="{{ route('member.index') }}"><i class="fas fa-users"></i><span>Member</span></a></li>
            <li><a class="nav-link" href="{{ route('ads.index') }}"><i class="fas fa-file-alt"></i><span>Iklan Baris</span></a></li>
            <li><a class="nav-link" href="{{ route('book.index') }}"><i class="fas fa-book"></i><span>Book</span></a></li>
            <li><a class="nav-link" href="{{ route('categories.index') }}"><i class="fas fa-list-alt"></i><span>Categories</span></a></li>
            <li><a class="nav-link" href="{{ route('contributor.index') }}"><i class="fab fa-black-tie"></i><span>Contributor</span></a></li>
            <li><a class="nav-link" href="{{ route('event.index') }}"><i class="fas fa-columns"></i><span>Event</span></a></li>
            {{-- <li><a class="nav-link" href="{{ route('categories.googlecloud') }}"><i class="fas fa-columns"></i><span>Google Cloud</span></a></li> --}}
        </ul>
    </aside>
</div>