routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');
Route::post('reset', 'Api\PasswordResetController@reset')->name('reset.password.api');
Auth::routes(['verify' => true]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth' => 'dashboard']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/subscriber', 'SubscribeController@index')->name('subscribe.index');
    Route::get('/subscriber/show/{pointer}', 'SubscribeController@show')->name('subscribe.show');

    Route::get('/member', 'MemberController@index')->name('member.index');
    Route::get('/member/show/{pointer}', 'MemberController@show')->name('member.show');

    Route::get('/contributor', 'DonationController@index')->name('contributor.index');
    Route::get('/contributor/show/{pointer}', 'DonationController@show')->name('contributor.show');

    Route::resource('event', 'EventController');

    Route::resource('book', 'BookController');

    Route::resource('ads', 'AdsController');

    Route::resource('categories', 'CategoriesController');
    Route::get('/googlecloud', 'CategoriesController@googlecloud')->name('categories.googlecloud');
    Route::post('/googlecloud', 'CategoriesController@googlecloudUpload')->name('categories.googlecloudUpload');
    Route::get('/googlecloud/op', 'CategoriesController@googlecloudOpen')->name('categories.googlecloudOpen');

});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'title',
        'thumbnail',
        'description',
        'category',
        'author',
        'book',
        'row_pointer',
        'created_by',
        'updated_by'
    ];
}

app/Http/Controllers/Api/BookController.php
<?php

namespace App\Http\Controllers\Api;

use App\Book;
use App\Http\Controllers\Controller;
use DB;

class BookController extends Controller
{
    public function getAll()
    {
        $data = Book::all();

        if (!empty($data)) {
            return response()->json([
                'status' => 'success',
                'code' => 200,
                'message' => 'Success',
                'data' => $data,
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'code' => 200,
            'message' => 'Record not found',
        ], 200);

    }
    public function show($pointer)
    {
        $data = Book::where('row_pointer', $pointer)->first();

        if (!empty($data)) {
            return response()->json([
                'status' => 'success',
                'code' => 200,
                'message' => 'Success',
                'book' => $data,
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'code' => 200,
            'message' => 'Record not found',
        ], 200);
    }
    public function addViewCount($pointer)
    {
        $data = Book::where('row_pointer', $pointer);
        $getData= $data->first();
        
        DB::beginTransaction();
        try {
            if ($getData == null) {
                return response()->json([
                    'status' => 'error',
                    'message' => 'data Kosong',
                ], 200);
            } else {
                $jumlah = $getData->view_count + 1;
                $data->update([
                    'view_count' => $jumlah,
                ]);
    
                //Book::where('row_pointer', $pointer)->update(['view_count' => $data->view_count + 1]);
                DB::commit();
                return response()->json([
                    'status' => 'success',
                    'message' => 'jumlah klik = '.$jumlah,
                ], 200);
            }
            

        } catch (Exception $e) {

            DB::rollBack();

            return response()->json([
                'status' => 'error',
                'message' => 'Book failed to update' . $e,
            ]);
        }
    }
    public function searchBook($name)
    {
        try {
            $book = Book::where('title', 'like', "%{$name}%")->orWhere('author', 'like', "%{$name}%")->get();
            if (count($book) == 0) {
                $data = 0;
            } else {
                $data = $book;
            }
        
            return response()->json([
                'status' => 'success',
                'message' => 'successfully',
                'data' => $data,
            ], 200);
        } catch (Exception $e) {

            DB::rollBack();

            return response()->json([
                'status' => 'error',
                'message' => 'book failed to search' . $e,
            ]);
        }

    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Carbon\Carbon;
use DB;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Image;
use Ramsey\Uuid\Uuid;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Book::all();

        return view('book.index', ['books' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = DB::table('categories')->get();
        return view('book.create', ['categories' => $data]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'thumbnail' => 'mimes:jpeg,jpg,png|required',
            'description' => 'required',
            'author' => 'required',
            'book' => 'required|mimes:pdf',
        ]);
        if ($request->thumbnail != null) {
            ///resize//
            $namagambar = time() . '.' . request()->thumbnail->getClientOriginalExtension();
            $img = Image::make($request->thumbnail->getRealPath());
            $img->resize(1080, 1920, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path() . '/upload/book/thumbnails/' . $namagambar, 80);
            ///resize//
            $fileCover = $request->thumbnail;
            $imageName = 'book/cover/cover' . time() . '.' . $fileCover->getClientOriginalExtension();
            Storage::disk('gcs')->put($imageName, File::get(public_path() . '/upload/book/thumbnails/' . $namagambar));
            Storage::disk('gcs')->setVisibility($imageName, 'public');
            // $urlcover = Storage::disk('gcs')->url($imageName);
            $file_path1 = public_path() . '/upload/book/thumbnails/' . $namagambar;
            if (File::exists($file_path1)) {
                File::delete($file_path1);
            }
        }
        if ($request->book != null) {
            $fileBook = $request->book;
            $bookName = 'book/pdf/pdf' . time() . '.' . $fileBook->getClientOriginalExtension();
            Storage::disk('gcs')->put($bookName, File::get($fileBook));
            Storage::disk('gcs')->setVisibility($bookName, 'public');
            // $urlpdf = Storage::disk('gcs')->url($bookName);
        }
        // request()->thumbnail->move(public_path() . '/upload/book/thumbnails/', $imageName);

        // $bookName = time() . '.' . request()->book->getClientOriginalExtension();

        // request()->book->move(public_path() . '/upload/book/files/', $bookName);

        Book::insert([
            'title' => $request->title,
            'thumbnail' => $imageName,
            'description' => $request->description,
            'category' => $request->category,
            'author' => $request->author,
            'book' => $bookName,
            'row_pointer' => Uuid::uuid4()->getHex(),
            'created_by' => Auth::user()->id,
            'created_at' => Carbon::now(),
        ]);

        return redirect()->route('book.index')->with('success', 'Book created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $data = DB::table('categories')->get();
        $urlcover = Storage::disk('gcs')->url($book->thumbnail);
        $urlbook = Storage::disk('gcs')->url($book->book);
        return view('book.edit', ['book' => $book, 'categories' => $data, 'urlcover' => $urlcover, 'urlbook' => $urlbook]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'author' => 'required',
        ]);
        $disk = Storage::disk('gcs');
        if ($request->thumbnail == null) {

            $imageName = $book->thumbnail;

        } else {
            $disk->delete($book->thumbnail);
            ///resize//
            $namagambar = time() . '.' . request()->thumbnail->getClientOriginalExtension();
            $img = Image::make($request->thumbnail->getRealPath());
            $img->resize(1080, 1920, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            })->save(public_path() . '/upload/book/thumbnails/' . $namagambar, 80);
            ///resize//
            $fileCover = $request->thumbnail;
            $imageName = 'book/cover/cover' . time() . '.' . $fileCover->getClientOriginalExtension();
            $disk->put($imageName, File::get(public_path() . '/upload/book/thumbnails/' . $namagambar));
            $disk->setVisibility($imageName, 'public');
            $file_path1 = public_path() . '/upload/book/thumbnails/' . $namagambar;
            if (File::exists($file_path1)) {
                File::delete($file_path1);
            }
        }

        if ($request->bookk == null) {

            $bookName = $book->book;

        } else {
            $disk->delete($book->book);
            $fileBook = $request->bookk;
            $bookName = 'book/pdf/pdf' . time() . '.' . $fileBook->getClientOriginalExtension();
            $disk->put($bookName, File::get($fileBook));
            $disk->setVisibility($bookName, 'public');

        }

        $book->update([
            'title' => $request->title,
            'thumbnail' => $imageName,
            'description' => $request->description,
            'category' => $request->category,
            'author' => $request->author,
            'book' => $bookName,
            'updated_by' => Auth::user()->id,
            'updated_at' => Carbon::now(),
        ]);

        return redirect()->route('book.index')->with('success', 'Book updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();
        Storage::disk('gcs')->delete($book->book);
        Storage::disk('gcs')->delete($book->thumbnail);
        return redirect()->route('book.index')->with('success', 'Book deleted successfully.');
    }
}

resources/views/book/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="#" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Create New Book</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{{ route('home') }}">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="{{ route('book.index') }}">Book</a></div>
                <div class="breadcrumb-item">Create New Book</div>
            </div>
        </div>

        <div class="section-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <h2 class="section-title">Create New Book</h2>
            <p class="section-lead">
                On this page you can create a new book and fill in all fields.
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Create New Book</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('book.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="title">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Thumbnail</label>
                                    <div class="col-sm-12 col-md-7">
                                        <div id="image-preview" class="image-preview" style="width: 500px;">
                                            <label for="image-upload" id="image-label">Choose File</label>
                                            <input type="file" name="thumbnail" id="image-upload"
                                                accept="image/gif, image/jpeg, image/png,image/jpg" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea name="description" id="" cols="30" rows="10"
                                            class="form-control"></textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select id="category" name="category" class="form-control" required>
                                            <option class="form-control" value="">Pilih Kategori Buku</option>
                                            @foreach ($categories as $item)
                                            <option class="form-control" value="{{$item->id}}">{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Author</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="author">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Book</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="file" class="form-control" name="book">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button class="btn btn-primary">Create Book</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/book/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="#" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Edit Book</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{{ route('home') }}">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="{{ route('book.index') }}">Book</a></div>
                <div class="breadcrumb-item">Edit Book</div>
            </div>
        </div>

        <div class="section-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <h2 class="section-title">Edit Book</h2>
            <p class="section-lead">
                On this page you can update a book and fill in all fields.
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Edit Your Book</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('book.update', $book->id) }}" method="post"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="title" value="{{ $book->title }}">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Thumbnail</label>
                                    <div class="col-sm-12 col-md-7">
                                        <div id="image-preview" class="image-preview"
                                            style="width: 500px; background-image: url('{{ 'https://storage.googleapis.com/bec_collection/'. $book->thumbnail }}'); background-size: 100% 100%;">
                                            <label for="image-upload" id="image-label">Choose File</label>
                                            <input type="file" name="thumbnail" id="image-upload"
                                                accept="image/gif, image/jpeg, image/png,image/jpg" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea name="description" id="" cols="30" rows="10"
                                            class="form-control">{{ $book->description }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Author</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="author"
                                            value="{{ $book->author }}">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Book</label>

                                    <div class="col-sm-12 col-md-7">
                                        {{'https://storage.googleapis.com/bec_collection/'. $book->book }}
                                        <input type="file" class="form-control" name="bookk">
                                    </div>

                                </div>

                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select id="category" name="category" class="form-control" required>
                                            @foreach ($categories as $item)
                                            <option class="form-control " value="{{$item->id}}"
                                                {{$item->id == $book->category ? 'selected' : ''}}>{{$item->name}}
                                            </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button class="btn btn-primary">Edit Book</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/book/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Book</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="{{ route('home') }}">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="{{ route('book.index') }}">Book</a></div>
                    {{--                    <div class="breadcrumb-item">DataTables</div>--}}
                </div>
            </div>

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="section-body">
                <h2 class="section-title">Book
                    <div class="float-right">
                        <a href="{{ route('book.create') }}" class="btn btn-primary">Create Book</a>
                    </div>
                </h2>
                <p class="section-lead">
                    List all book
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Book</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-1">
                                        <thead>
                                        <tr>
                                            <th class="text-center" width="8%">
                                                #
                                            </th>
                                            <th>Title</th>
                                            <th>Click</th>
                                            <th>Thumbnail</th>
                                            <th width="20%">Description</th>
                                            <th>author</th>
                                            <th width="15%">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($books as $index => $book)
                                            <tr>
                                                <td class="text-center">{{ $index+1 }}</td>
                                                <td>{{ $book->title }}</td>
                                                <td>{{$book->view_count}}</td>
                                                <td><img id="img" src="{{'https://storage.googleapis.com/bec_collection/'.$book->thumbnail }}" alt="" style="width: 100%; max-width: 100px; height: auto;"></td>
                                                <td>{{ \Illuminate\Support\Str::limit(strip_tags($book->description), '100', ' ...') }}</td>
                                                <td>{{ $book->author }}</td>
                                                <td>
                                                    <form action="{{ route('book.destroy', $book->id) }}" method="post">
                                                        <a href="{{ route('book.edit', $book->id) }}" class="btn btn-warning">Edit</a>

                                                        @csrf
                                                        @method('DELETE')

                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop