routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');
Route::post('reset', 'Api\PasswordResetController@reset')->name('reset.password.api');
Auth::routes(['verify' => true]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth' => 'dashboard']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/subscriber', 'SubscribeController@index')->name('subscribe.index');
    Route::get('/subscriber/show/{pointer}', 'SubscribeController@show')->name('subscribe.show');

    Route::get('/member', 'MemberController@index')->name('member.index');
    Route::get('/member/show/{pointer}', 'MemberController@show')->name('member.show');

    Route::get('/contributor', 'DonationController@index')->name('contributor.index');
    Route::get('/contributor/show/{pointer}', 'DonationController@show')->name('contributor.show');

    Route::resource('event', 'EventController');

    Route::resource('book', 'BookController');

    Route::resource('ads', 'AdsController');

    Route::resource('categories', 'CategoriesController');
    Route::get('/googlecloud', 'CategoriesController@googlecloud')->name('categories.googlecloud');
    Route::post('/googlecloud', 'CategoriesController@googlecloudUpload')->name('categories.googlecloudUpload');
    Route::get('/googlecloud/op', 'CategoriesController@googlecloudOpen')->name('categories.googlecloudOpen');

});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'title',
        'description',
        'street',
        'location',
        'image',
        'date_start',
        'date_end',
        'created_by',
        'updated_by'
    ];
}

app/Http/Controllers/Api/EventController.php
<?php

namespace App\Http\Controllers\Api;

use App\Event;
use App\Book;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class EventController extends Controller
{
    public function getAll()
    {
        //$data = Event::where('date_start','<=',Carbon::now())->where('date_end','>=',Carbon::now())->get();
$data = Event::get();
        if (!empty($data)) {
            return response()->json([
                'status' => 'success',
                'code' => 200,
                'message' => 'Success',
                'events' => $data
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'code' => 200,
            'message' => 'Record not found',
        ], 200);

    }
    public function getHomeData()
    {
        $event = Event::all();
        $booknew = Book::orderBy('id','desc')->get();
        $book = Book::inRandomOrder()->limit(4)->get();
        $bookRandom = Book::inRandomOrder()->limit(4)->get();
        $bookPopular = Book::orderBy('view_count','desc')->take(4)->get();

        if (!empty($book)) {
            return response()->json([
                'status' => 'success',
                'code' => 200,
                'message' => 'Success',
                'events' => $event,
                'booknew'=>$booknew,
                'books' => $book,
                'random'=>$bookRandom,
                'booksPopular' => $bookPopular
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'code' => 200,
            'message' => 'Record not found',
        ], 200);

    }

    public function show($pointer)
    {
        $data = Event::where('row_pointer', $pointer)->first();

        if (!empty($data)) {
            return response()->json([
                'status' => 'success',
                'code' => 200,
                'message' => 'Success',
                'event' => $data
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'code' => 200,
            'message' => 'Record not found',
        ], 200);
    }
    public function viewCounter($pointer)
    {
        $data = Event::where('row_pointer', $pointer);
        $getData= $data->first();
        
        DB::beginTransaction();
        try {
            if ($getData == null) {
                return response()->json([
                    'status' => 'error',
                    'message' => 'data Kosong',
                ], 200);
            } else {
                $jumlah = $getData->view_count + 1;
                $data->update([
                    'view_count' => $jumlah,
                ]);
    
                //Book::where('row_pointer', $pointer)->update(['view_count' => $data->view_count + 1]);
                DB::commit();
                return response()->json([
                    'status' => 'success',
                    'message' => 'jumlah klik = '.$jumlah,
                ], 200);
            }
            

        } catch (Exception $e) {

            DB::rollBack();

            return response()->json([
                'status' => 'error',
                'message' => 'Event failed to update' . $e,
            ]);
        }
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;
use Illuminate\Support\Facades\File;
use Image;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Event::all();

        return view('event.index', ['events' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('event.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'image' => 'mimes:jpeg,jpg,png|required|max:40000',
            'date_start' => 'required',
            'date_end' => 'required'
        ]);

        // $imageName = time() . '.' . request()->image->getClientOriginalExtension();

        // request()->image->move(public_path() . '/upload/events/', $imageName);
        $imageName = time() . '.' . request()->image->getClientOriginalExtension();
        $img = Image::make($request->image->getRealPath());
        $img->resize(1080, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        })->save(public_path() . '/upload/events/'. $imageName, 80);

        Event::insert([
            'title' => $request->title,
            'location' => $request->location,
            'street' => $request->street,
            'description' => $request->description,
            'image' => $imageName,
            'date_start' => $request->date_start,
            'date_end' => $request->date_end,
            'row_pointer' => Uuid::uuid4()->getHex(),
            'created_by' => Auth::user()->id,
            'created_at' => Carbon::now()
        ]);

        return redirect()->route('event.index')->with('success','Event created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('event.edit', ['event' => $event]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'location'=>'required',
            'street' => 'required',
        ]);
        if ($request->image != null) {
            $file_path1 = public_path("upload/events/" . $event->image);
            if (File::exists($file_path1)) {
                File::delete($file_path1);
            }
            $imageName = time() . '.' . request()->image->getClientOriginalExtension();
            $img = Image::make($request->image->getRealPath());
            $img->resize(1080, null, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            })->save(public_path() . '/upload/events/'. $imageName, 80);

        } else {

            $imageName = $event->image;

        }
        if($request->date_start == null){
            $mulai = $request->date_start_lama;
        }else{
            $mulai = $request->date_start;
        }
        if($request->date_end == null){
            $akhir = $request->date_end_lama;
        }else{
            $akhir = $request->date_end;
        }

        $event->update([
            'title' => $request->title,
            'description' => $request->description,
            'location' => $request->location,
            'street' => $request->street,
            'image' => $imageName,
            'date_start' => $mulai,
            'date_end' => $akhir,
            'updated_by' => Auth::user()->id,
            'updated_at' => Carbon::now()
        ]);

        return redirect()->route('event.index')->with('success','Event updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        $file_path1 = public_path("upload/events/" . $event->image);

        if (File::exists($file_path1)) {
            File::delete($file_path1);
        }
        $event->delete();

        return redirect()->route('event.index')->with('success','Event deleted successfully.');
    }
}

resources/views/event/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="#" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Create New Event</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{{ route('home') }}">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="{{ route('event.index') }}">Event</a></div>
                <div class="breadcrumb-item">Create New Event</div>
            </div>
        </div>

        <div class="section-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <h2 class="section-title">Create New Event</h2>
            <p class="section-lead">
                On this page you can create a new event and fill in all fields.
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Create Your Event</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('event.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="title" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Location</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="location" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Street</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="street" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea name="description" id="" cols="30" rows="10"
                                            class="form-control" required></textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image
                                        Event</label>
                                    <div class="col-sm-12 col-md-7">
                                        <div id="image-preview" class="image-preview" style="width: 500px;">
                                            <label for="image-upload" id="image-label">Choose File</label>
                                            <input type="file" name="image" id="image-upload"
                                            accept="image/gif, image/jpeg, image/png,image/jpg" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date
                                        Start</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="datetime-local" class="form-control" name="date_start" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date
                                        End</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="datetime-local" class="form-control" name="date_end" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button class="btn btn-primary">Create Event</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/event/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="#" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Edit Event</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{{ route('home') }}">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="{{ route('event.index') }}">Event</a></div>
                <div class="breadcrumb-item">Edit Event</div>
            </div>
        </div>

        <div class="section-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <h2 class="section-title">Edit Event</h2>
            <p class="section-lead">
                On this page you can update a event and fill in all fields.
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Edit Your Event</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('event.update', $event->id) }}" method="post"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="title"
                                            value="{{ $event->title }}">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Location</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="location"
                                            value="{{ $event->location }}" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Street</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" class="form-control" name="street"
                                            value="{{ $event->street }}" required>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label
                                        class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea name="description" id="" cols="30" rows="10"
                                            class="form-control">{{ $event->description }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image
                                        Event</label>
                                    <div class="col-sm-12 col-md-7">
                                        <div id="image-preview" class="image-preview"
                                            style="width: 500px; background-image: url('{{ asset('upload/events/'. $event->image) }}'); background-size: 100% 100%;">
                                            <label for="image-upload" id="image-label">Choose File</label>
                                            <input type="file" name="image" id="image-upload" accept="image/gif, image/jpeg, image/png,image/jpg"  />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date
                                        Start</label>

                                    <div class="col-sm-12 col-md-7">
                                        {{ $event->date_start }}
                                        <input type="datetime-local" class="form-control" name="date_start"
                                            value="{{ $event->date_start }}">
                                        <input style="display: none" type="text" class="form-control"
                                            name="date_start_lama" value="{{ $event->date_start }}">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date
                                        End</label>
                                    <div class="col-sm-12 col-md-7">
                                        {{ $event->date_end }}
                                        <input type="datetime-local" class="form-control" name="date_end"
                                            value="{{ $event->date_end }}">
                                        <input style="display: none" type="text" class="form-control"
                                            name="date_end_lama" value="{{ $event->date_end }}">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button class="btn btn-primary">Edit Event</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/event/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Event</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="{{ route('home') }}">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="{{ route('event.index') }}">Event</a></div>
                    {{--                    <div class="breadcrumb-item">DataTables</div>--}}
                </div>
            </div>

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="section-body">
                <h2 class="section-title">Event
                    <div class="float-right">
                        <a href="{{ route('event.create') }}" class="btn btn-primary">Create Event</a>
                    </div>
                </h2>
                <p class="section-lead">
                    List all event
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Event</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-1">
                                        <thead>
                                        <tr>
                                            <th class="text-center" width="2%">
                                                #
                                            </th>
                                            <th>Title</th>
                                            <th>Click</th>
                                            <th width="20%">Description</th>
                                            <th>Image</th>
                                            <th>Start</th>
                                            <th>End</th>
                                            <th width="15%">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($events as $index => $event)
                                            <tr>
                                                <td class="text-center">{{ $index+1 }}</td>
                                                <td>{{ $event->title }}</td>
                                                <td>{{$event->view_count}}</td>
                                                <td>{{ \Illuminate\Support\Str::limit(strip_tags($event->description), '100', ' ...') }}</td>
                                                <td><img src="{{ asset('upload/events/'. $event->image) }}" alt="" style="width: 100%; max-width: 100px; height: auto;"></td>
                                                <td>{{ \Carbon\Carbon::parse($event->date_start)->format('d-m-Y') }}</td>
                                                <td>{{ \Carbon\Carbon::parse($event->date_end)->format('d-m-Y') }}</td>
                                                <td>
                                                    <form action="{{ route('event.destroy', $event->id) }}" method="post">
                                                        <a href="{{ route('event.edit', $event->id) }}" class="btn btn-warning">Edit</a>

                                                        @csrf
                                                        @method('DELETE')

                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop